version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: directory-postgres
    environment:
      POSTGRES_DB: directory_db
      POSTGRES_USER: directory_user
      POSTGRES_PASSWORD: directory_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - directory-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directory_user -d directory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: directory-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - directory-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: directory-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      USE_MOCK: "true"
      DATABASE_URL: postgresql://directory_user:directory_password@postgres:5432/directory_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: development_jwt_secret_key_32_chars
      ENCRYPTION_KEY: development_encryption_key_32_chars
      LOG_LEVEL: debug
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - directory-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: directory-frontend
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_USE_MOCK: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - directory-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  directory-network:
    driver: bridge
